# Here is an example about how you can have the secrets required to run cloud-controller-manager.
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
  namespace: kube-system
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: '<base 64 cloudflare api token>'
  CLOUDFLARE_ZONE_ID: '<base 64 cloudflare zone id>'
  CLOUDFLARE_ACCOUNT_ID: '<base 64 cloudflare account id''
