name: Build Docker Images

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/clyentsoftwares/cloudflare-cloud-controller-manager:${{ github.event.release.tag_name }}
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
